### ISSUE TITLE
setup.py install error "ImportError: No module named PyQt4"

### ISSUE THREAD

**Issue by jcmaslan** [tnc-ca-geo/video-importer#15]
I'm pasting the complete output from having run the command:
```shell
python setup.py install
```

But

```
Carters-MacBook-Pro:video-importer carter$ python setup.py install
running install
running bdist_egg
running egg_info
creating import_video.egg-info
writing requirements to import_video.egg-info/requires.txt
writing import_video.egg-info/PKG-INFO
writing top-level names to import_video.egg-info/top_level.txt
writing dependency_links to import_video.egg-info/dependency_links.txt
writing entry points to import_video.egg-info/entry_points.txt
writing manifest file 'import_video.egg-info/SOURCES.txt'
reading manifest file 'import_video.egg-info/SOURCES.txt'
writing manifest file 'import_video.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying import_video.py -> build/lib
creating build/bdist.macosx-10.6-x86_64
creating build/bdist.macosx-10.6-x86_64/egg
copying build/lib/import_video.py -> build/bdist.macosx-10.6-x86_64/egg
byte-compiling build/bdist.macosx-10.6-x86_64/egg/import_video.py to import_video.pyc
creating build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying import_video.egg-info/PKG-INFO -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying import_video.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying import_video.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying import_video.egg-info/entry_points.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying import_video.egg-info/requires.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying import_video.egg-info/top_level.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
import_video: module references __file__
creating dist
creating 'dist/import_video-0.1-py2.7.egg' and adding 'build/bdist.macosx-10.6-x86_64/egg' to it
removing 'build/bdist.macosx-10.6-x86_64/egg' (and everything under it)
Processing import_video-0.1-py2.7.egg
creating /Users/carter/anaconda/lib/python2.7/site-packages/import_video-0.1-py2.7.egg
Extracting import_video-0.1-py2.7.egg to /Users/carter/anaconda/lib/python2.7/site-packages
Adding import-video 0.1 to easy-install.pth file
Installing import_video script to /Users/carter/anaconda/bin

Installed /Users/carter/anaconda/lib/python2.7/site-packages/import_video-0.1-py2.7.egg
Processing dependencies for import-video==0.1
Searching for hachoir_metadata
Reading https://pypi.python.org/simple/hachoir_metadata/
Best match: hachoir-metadata 1.3.3
Downloading https://pypi.python.org/packages/98/89/f31ba1431ed7627032338cd009eaeb65dfad1311fa1437107c406fcb025e/hachoir-metadata-1.3.3.tar.gz#md5=26e04a2395205d31469fc2d6935055a9
Processing hachoir-metadata-1.3.3.tar.gz
Writing /var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-6nUpFX/hachoir-metadata-1.3.3/setup.cfg
Running hachoir-metadata-1.3.3/setup.py -q bdist_egg --dist-dir /var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-6nUpFX/hachoir-metadata-1.3.3/egg-dist-tmp-kyJXoj
Traceback (most recent call last):
  File "/Users/carter/anaconda/lib/python2.7/site-packages/PyQt4/uic/pyuic.py", line 26, in <module>
    from PyQt4 import QtCore
ImportError: No module named PyQt4
Warning: unable to recompile dialog.ui to dialog_ui.py using pyuic4
(use command "/var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-6nUpFX/hachoir-metadata-1.3.3/setup.py -q bdist_egg --dist-dir /var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-6nUpFX/hachoir-metadata-1.3.3/egg-dist-tmp-kyJXoj --disable-qt" to disable this warning)

zip_safe flag not set; analyzing archive contents...
Copying hachoir_metadata-1.3.3-py2.7.egg to /Users/carter/anaconda/lib/python2.7/site-packages
Adding hachoir-metadata 1.3.3 to easy-install.pth file
Installing hachoir-metadata-qt script to /Users/carter/anaconda/bin
Installing hachoir-metadata-gtk script to /Users/carter/anaconda/bin
Installing hachoir-metadata script to /Users/carter/anaconda/bin

Installed /Users/carter/anaconda/lib/python2.7/site-packages/hachoir_metadata-1.3.3-py2.7.egg
Searching for hachoir_parser
Reading https://pypi.python.org/simple/hachoir_parser/
Best match: hachoir-parser 1.3.4
Downloading https://pypi.python.org/packages/6a/ad/037c6b8a614c7f8d4eeb2993bf19ad4ea19a9506d268f808e10644081286/hachoir-parser-1.3.4.tar.gz#md5=e578b779c4b30d94ca4e775747877755
Processing hachoir-parser-1.3.4.tar.gz
Writing /var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-36Q1Gd/hachoir-parser-1.3.4/setup.cfg
Running hachoir-parser-1.3.4/setup.py -q bdist_egg --dist-dir /var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-36Q1Gd/hachoir-parser-1.3.4/egg-dist-tmp-ep1Bco
warning: no files found matching 'metadata_csv.py'
zip_safe flag not set; analyzing archive contents...
Copying hachoir_parser-1.3.4-py2.7.egg to /Users/carter/anaconda/lib/python2.7/site-packages
Adding hachoir-parser 1.3.4 to easy-install.pth file

Installed /Users/carter/anaconda/lib/python2.7/site-packages/hachoir_parser-1.3.4-py2.7.egg
Searching for hachoir_core
Reading https://pypi.python.org/simple/hachoir_core/
Best match: hachoir-core 1.3.3
Downloading https://pypi.python.org/packages/26/c1/2d2e5996c7488bdc2d3dcd14de5ace6e8f8f334b4896e932a21d5572cdfc/hachoir-core-1.3.3.tar.gz#md5=b80f0257536e2b2cb23f66670c4f6f31
Processing hachoir-core-1.3.3.tar.gz
Writing /var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-MYkpYG/hachoir-core-1.3.3/setup.cfg
Running hachoir-core-1.3.3/setup.py -q bdist_egg --dist-dir /var/folders/61/jzjlj5v50hxcxbmnb95qy_740000gn/T/easy_install-MYkpYG/hachoir-core-1.3.3/egg-dist-tmp-IkCShs
zip_safe flag not set; analyzing archive contents...
hachoir_core.i18n: module references __file__
creating /Users/carter/anaconda/lib/python2.7/site-packages/hachoir_core-1.3.3-py2.7.egg
Extracting hachoir_core-1.3.3-py2.7.egg to /Users/carter/anaconda/lib/python2.7/site-packages
Adding hachoir-core 1.3.3 to easy-install.pth file

Installed /Users/carter/anaconda/lib/python2.7/site-packages/hachoir_core-1.3.3-py2.7.egg
Searching for psutil==4.3.0
Best match: psutil 4.3.0
Adding psutil 4.3.0 to easy-install.pth file

Using /Users/carter/anaconda/lib/python2.7/site-packages
Searching for requests==2.10.0
Best match: requests 2.10.0
Adding requests 2.10.0 to easy-install.pth file

Using /Users/carter/anaconda/lib/python2.7/site-packages
Finished processing dependencies for import-video==0.1
```

**Comment by jhallard** [comment]
@mdipierro why would we have a qt dependency? Is that something that hachoir brings with it?

```
Traceback (most recent call last):
  File "/Users/carter/anaconda/lib/python2.7/site-packages/PyQt4/uic/pyuic.py", line 26, in <module>
    from PyQt4 import QtCore
ImportError: No module named PyQt4
Warning: unable to recompile dialog.ui to dialog_ui.py using pyuic4
```
